name: Github CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pipeline:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Create env file'
        run: |
          touch .env
          echo SECRET=${{ secrets.SECRET }} >> .env
          echo DB_CONNECTION_TEST=${{ secrets.DB_CONNECTION_TEST }} >> .env
          echo DB_CONNECTION_PRESENTATION=${{ secrets.DB_CONNECTION_PRESENTATION }} >> .env
          cat .env

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install
        
      - name: Run Tests
        run: npm test
